js2-mode.el

This adds two functions to the browser externs list:
- `requestAnimationFrame`
- `cancelAnimationFrame`
See http://www.w3.org/TR/animation-timing/#requestAnimationFrame for
details.

Add animationFrame functions

---

js2-mode.el

remove unused variable inside `js2-time' function.

`js2-time' remove unused variable.

---

js2-mode.el
tests/parser.el

do auto semicolon insert on function exports

---

js2-mode.el
tests/parser.el

Don't treat getter / setter pairs as duplicates

---

README.md

Add melpa badges to the README

Add melpa badges

---

NEWS.md
js2-mode.el
js2-old-indent.el
tests/indent.el

Complements the [latest change to master](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=958da7ff63d1d647f45fd649654136da78529324). Partially resolves #140.

Add js2-jsx-mode

---

js2-mode.el
tests/json-path.el

place the cursor above key/value to print the json path which is also pushed into kill-ring

`js2-print-json-path' added

---

NEWS.md
README.md
js2-mode.el
tests/parser.el

Conflicts resolved are listed in the message of merge commit.
I noticed branch `nil` tried to implement async methods, but quite incomplete.  So I wrote async methods myself.

Adapt old async to master & async methods

---

js2-mode.el

No idea how to test this.  Required?

Colorize contextual keyword as in import & export

---

Makefile

Makefile: use -Q to avoid site-lisp loading

---

js2-mode.el

Fixes #379
Note that this PR somewhat depends on the outcome of douglascrockford/JSLint#196 and/or douglascrockford/JSLint#197.

Fix dead link in the documentation

---

Makefile
js2-mode.el
tests/consume.el

See issue https://github.com/mooz/js2-mode/issues/383
Will squash into 1 commit if the PR become mergable.

feat: add js2-comments-between func

---

js2-mode.el
tests/consume.el

make sure to visit import clause children in order

---

js2-mode.el

http://usejsdoc.org/tags-yields.html

Add jsdoc highlighting for yield and yields

---

js2-mode.el

Add separate object property access face

---

js2-mode.el

http://usejsdoc.org/tags-abstract.html

Add jsdoc @abstract/@virtual empty tags

---

js2-mode.el
tests/parser.el

This handles most common cases of the `import` statement, see the tests.
I would not be surprised if there is a wider set of syntaxes... if so, please give me samples and I will try to cover them too.

Classify imported variables

---

README.md

Avoid redirection in README.md

---

js2-mode.el
tests/parser.el

I don’t really know what I’m doing, but maybe this can be a start.
For https://github.com/mooz/js2-mode/issues/559

start implementing NULLISH-COALESCING, likely incomplete

---

.github/workflows/test.yml

Unit tests will now be executed for every PR.

Add GitHub Actions workflow

---

.github/workflows/test.yml
NEWS.md
js2-imenu-extras.el
tests/imenu-mocha.el

Support mocha-like test files in Imenu

---

NEWS.md
js2-mode.el
tests/parser.el

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#advanced_searching_with_flags

Add support for the d (hasIndices) and s (dotAll) regexp flags
