js2-mode.el
tests/parser.el

Fixes [\#218](https://github.com/mooz/js2-mode/issues/218).
See [here](https://github.com/mooz/js2-mode/issues/218#issuecomment-76540657) for more info.

Fix off-by-one error for comment node length

---

js2-mode.el

Previously this function discriminated against nodes that did not have parents. For such nodes, `nil` should have been returned, but instead an error was emitted, because a parentless node would produce the initial parent `nil` which would cause `js2-node-parent` to blow up. This fixes that.
Originally this was going to be a throw-in for [\#219](https://github.com/mooz/js2-mode/pull/219), but considering we might not merge that in, I'd like to get this fix in so I can move forward on a `js2-refactor` version of [\#219](https://github.com/mooz/js2-mode/pull/219).

Fix js2-node-get-enclosing-scope

---

js2-mode.el
tests/indent.el

I liked how `js2-mode` indented multiline `var` statements, for the most part. But when it came to function expressions and object/array literals, I felt that the settings fell short.
With `(setq js2-pretty-multiline-declarations t)`, I got this:
```js
var a = function () {
// Body.
};
```
But I also got this:
```js
var a = function () {
// Body.
},
b = function () {
// Body.
};
```
I did not like how the function bodies didn't align nicely.
So when I tried `(setq js2-pretty-multiline-declarations 'all)`, I was happy to find that I got this:
```js
var a = function () {
// Body.
},
b = function () {
// Body.
};
```
But then I got this too:
```js
var a = function () {
// Body.
};
```
If there isn't another function in the `var` declaration to align against, the indentation seems …

js2-pretty-multiline-declarations: Add 'dynamic option

---

js2-mode.el
tests/parser.el

This allows e.g. {[a + b]() {...}}, {'foo'() {...}}, and {get [a + b]() {...}}.
Previously, short-hand functions/getters/setters/generators only worked for unquoted names.  Now we support all combinations of key types (name, string, number, computed) with all property types (colon-delimited, getter, setter, generator, and short-hand functions).

Generalize object literal parsing to understand computed function names.

---

js2-mode.el

Forgive me if I'm missing something, but I don't see why this variable is being unset.
It would be useful if it was still set, especially if a minor mode wanted to analyze the identifiers from `js2-mode`'s initial parse. Before this change, a minor mode would have to set up a `js2-post-parse-callback` and reparse for no reason in order to get access to the `js2-recorded-identifiers`.

Don't unset `js2-recorded-identifiers'

---

NEWS.md
js2-mode.el
tests/parser.el

This is the PR for refactor as you wanted @dgutov.
Something to note:
- method-node is still an infix node, but its right, the function, is now named (more closely follows standard);
- its left, the property, is not a child of the method node, but instead a child of the right side function node (duplicated in the tree).
These allows `js2-infix-node-left` and `js2-infix-node-right` to be still able to access the key and value of a method node.  Another option is to make method-node inherit directly from the base node, and add new functions `js2-property-key` and `js2-property-value`.  Quite some functions need change; I am not sure if I can catch all of them by looking at test results.
Please tell whether you like the current implementation or the other option.  It may need careful reviews …

Rename getter-setter-node to method-node

---

js2-mode.el
tests/parser.el

This is published ES6.  Do you want more tests?  I admit the test is a little too simple.

Allow semicolons in a class body

---

NEWS.md
js2-mode.el
tests/parser.el

Also published ES6.  This implementation happens to allow ES7 stage 1 property initializers https://github.com/jeffmo/es-class-static-properties-and-fields.
Perhaps this can fix #205.

Add default parameters support to destructuring

---

js2-mode.el
tests/parser.el

0o octals are allowed in ES6 strict mode, while octals like 0123 are
called LegacyOctalIntegerLiteral and remain disallowed.
New style octals are used in nodejs code.

Allow 0o octals in strict mode

---

js2-mode.el
tests/parser.el

`function foo(bar, {a = {}} = {}) {/**/}`
Fixes the original test case in #205.
What I did (see if it looks right):
* Pulled `(push param params)` out of the `cond`, since it happens no matter what
* Pulled `;; default parameter value` handling out of the `cond`, so that it happens even for the destructuring case
* Added the check `(not rest-param-at)` to `;; default parameter value` handling so that it doesn't trigger in case of a rest param
I added a test but I did not run the tests.
The existing NEWS item should cover this change.

Fix parsing of param with destructure and default

---

js2-mode.el
tests/parser.el

In the following code, no semicolons should be considered missing,
and all of A,B,C,D should be considered declared.
```
export function A() {}
export class B {}
export default function C() {}
export default class D {}
var x = [A, B, C, D];
```
This should fix #215.
The approach here of parsing functions and classes as statements seems to work.
See also;
* [`export` language grammar](http://www.ecma-international.org/ecma-262/6.0/#sec-exports)
* [Discussion of semicolons over at eslint](https://github.com/eslint/eslint/issues/2194)

Fix semicolons and scoping in exported decls

---

js2-mode.el

Declarations in for-of and for-in loops may also be "const".  See
http://www.ecma-international.org/ecma-262/6.0/#sec-runtime-semantics-bindinginstantiation

Recognize for-of and for-in loops with const

---

js2-mode.el
tests/parser.el

Fixes some parsing errors with unary expressions.
A little while ago I observed the issue described in #300, and finally I was spurred to fix it. I discovered `js2-match-async-arrow-function` caused an off-by-one error, so I prevented that.
I also noticed that `await` parsing was too eager, so I added an extra guard there.
I also noticed that `void` was not being printed correctly with `js2-print-tree`, so I fixed that too.

Fix void async await

---

js2-mode.el
tests/parser.el

This change enables proper parsing of:
* `let [a, b, ...c] = d;`
* `let [[x,y] = [1,2]] = z;`
The first case is simply the "rest" part of "array rest/spread," which
lacked the appropriate cases in `js2-parse-array-literal` and
`js2-define-destruct-symbols`.  There's also new logic to make sure that
in the destructuring (rest) case, the rest element comes last (while
spread can occur anywhere).
The removal of the `;; destructuring bind` case of
`js2-parse-array-literal` may require some explanation.  It was doing
more harm than good.  For example, it assumed that only identifiers
have defaults.  Also, calling `js2-parse-destruct-primary-expr` is
unnecessary, since `js2-is-in-destructuring` is already true.  Rather
than add the triple-dot logic in two places, it was simpler to stop …

Fix array destructuring including triple-dot

---

js2-mode.el

The ECMAScript spec says
(http://www.ecma-international.org/ecma-262/5.1/#sec-10.5) that
declaring an already declared variable is silently ignored, so claiming
it's a TypeError is not correct. It should still be highlighted as a
warning because it's not something that any program should do and with
let redeclaration actually is a TypeError.

Change warning message to not conflict with spec

---

js2-mode.el
tests/externs.el

I added the allowance for an optional space in a global declaration. 
Eslint syntax for global declarations differs slightly from jslint, and this change makes that syntax considered valid.

Allow space before global declaration

---

js2-mode.el
tests/parser.el

As discussed in #245, this syntax is not part of ES6/2015, but it is
a stage 2 proposal, meaning the committee expects it to be included
in the standard.  It's already seeing heavy use by e.g. the React
community.
This change causes `...expr` in an object literal to be parsed as a
unary-node element of an object-node, and modifies places where an
element of an object-node is expected to be an infix-node.  Note that
only weak typing assumptions are made already about object-node elems.
In addition, this change implements proper name extraction in
object literal destructuring.  The cases are:
1. `let {a} = x;`
2. `let {a: b} = x;` (should define `b`)
3. `let {a = b} = x;` (should define `a`)
4. `let {...a} = x;` (should define `a`)
This change fixes case (2), which was broken, and adds case …

Implement object literal rest/spread (...)

---

js2-mode.el

This allows all files to be parsed as if 'use strict' were on top of every file, for the case of JS passed through compilers that assume strict input.
Closes #341.

Add js2-mode-assume-strict custom variable.

---

js2-mode.el

This patch will make "quoted name" use font-lock-function-name-face just
like {"quoted name": function () {...}} does.
I tried to write a test for this but could find no existing tests for checking
face settings.

Fix Highlighting function name of form {"quoted name" () {...}}

---

js2-mode.el

Reference: http://lists.gnu.org/archive/html/emacs-devel/2016-07/msg00297.html

js2-jsx-mode docstring fix

---

js2-mode.el
tests/parser.el

Noticed `{ async delete() {} }` parsed incorrectly, and this is a fix.

Special methods should allow keywords as names

---

NEWS.md
js2-mode.el

Instead of only taking into account the `js2-include-?-externs`
variables when initializing the mode, compute what was
`js2-default-externs` before every time we highlight undeclared
identifiers.
Closes #375
In the documentation for `js2-default-externs` it says that **at the moment** the externs are only used to highlight undeclared variables, so I thought a bit about how I can keep my changes very general so that one might use the resulting code for other purposes as well. Since I don't know the code very well, though, I decided YAGNI (for now) and went for the simplest solution (the first one in #375).
I also refactored the documentation a bit correspondingly.
Note that a consequence of these changes is that, other than by overriding `js2-ecma-262-externs` itself, you can now no longer …

Compute externs on demand

---

js2-mode.el

Currently the make-js2-template-node and make-js2-tagged-template-node constructors take a "beg" argument, which does not set the js2-node "pos" field. The pos field not being set causes incorrect results from, for example, js2-node-at-point with the point inside a template literal placeholder.
The only change here is to rename "beg" to "pos" in the constructors and call sites. 
I'm happy to make any changes needed to get this merged. Please let me know if this change needs any new test cases.

Fix "pos" argument in template node constructors

---

js2-mode.el

Should be `(- (js2-current-token-end) (js2-current-token-beg))` rather
than just `(js2-current-token-end)`.
Also change `if` to `cond` (seems easier to read in this case).

Fix length of name in namespace-import nodes

---

js2-mode.el

My previous patch breaks error detection when
`js2-recover-from-parse-errors` is non-nil.  This fixes it, sorry about that.

Fix the fix (error detection)

---

js2-mode.el

The need for disabling specific warning messages has come up a few times.
I've seen that there have been changes made to support disabling specific warnings such as dangling commas and no semicolons, but there's not a blanket method for disabling anything you want.
This was discussed shortly in #260, but a conclusion wasn't reached.
This is a much smaller first-class version of the functionality I've built in my own config: https://github.com/jordonbiondo/.emacs.d/blob/master/init.el#L901
Let me know what you think about the possibility of this feature being accepted using this method or any other.

Allow specific warnings to be ignored

---

js2-mode.el
tests/parser.el

`msg.yield.parenthesized` error is simply dropped, together with another fix, it parses the code example in that issue fine.  Wrapped in a generator function, of course.

Fix some yield parsing (#362)

---

js2-mode.el
tests/parser.el

For #359.
Looking at the proposal text I am not sure whether I should allow
``` js
class C {
x
y
}
```
Babel allows it, but babel disagrees with the proposal in rejecting computed names, which seems fine to me.  Which one is correct?

Add support for ES7 class public fields

---

NEWS.md
js2-mode.el
tests/parser.el

Fixes #403 
I'd like to add a unit test for this, but I don't really know where to start since I'm new to emacs lisp and emacs mode development. There doesn't seem to be a unit test for `js2-parse-function-params` in `tests/parse.el`. Do you think its worth adding one?

Allow trailing comma in param list

---

js2-mode.el

In Emacs, `indent-new-comment-line` is bound to both `M-j` and `C-M-j`. `js2-mode` remapped `M-j` to `js2-line-break`, but didn't remap `C-M-j`. This commit fixes that by telling Emacs to remap *all* bindings for `indent-new-comment-line` (currently, just `M-j` and `C-M-j`) to `js2-line-break`.

Map C-M-j to js2-line-break

---

js2-mode.el
tests/parser.el

Includes a slight restructuring of how side-effect calculations are done (for better testability) and adds basic test coverage for no.side.effect warnings.

Add option js2-getprop-has-side-effects

---

js2-mode.el

Some of the tags in js2-jsdoc-arg-tag-regexp (specifically `@this`, `@throws`, and `@type`) are used with braces by Closure Compiler. Previously the close-brace was styled differently from the open-brace.  Adding a branch to the regex for optional braces fixes this.

Fix jsdoc highlighting for tags w/ optional braces

---

js2-mode.el
tests/externs.el

Closes #237
I based this heavily on (and reused parts of) the mechanics to support `/*global*/` declarations. The lists of externs for the different declarations is lifted directly from the [JSLint documentation](http://www.jslint.com/help.html).

Add support for /*jslint*/ declarations

---

js2-mode.el
tests/consume.el

Arrow functions are always expressions, so `js2-node-parent-stmt` should
continue recursing to their parent to find the first statement. This could happen
either because it is called with the arrow function node to begin with, or if the
arrow function is brace-less, in which case it doesn't wrap its expression in `js2-expr-stmt-node`

Correctly handle arrow functions in js2-node-parent-stmt

---

NEWS.md
js2-mode.el
tests/parser.el

Fixes #453 
I've tested this using `make test` and also installed patched version locally. For now there are no errors/warnings for this code:
<details>
<summary>Trailing comma in: import, function declaration/call, array, object, export</summary>
```javascript
import {
a,
b,
} from 'package';
function f (
a,
b,
) {}
f(
1,
2,
);
const array = [
1,
2,
];
const object = {
a,
b,
};
export {
a,
f,
};
```
</details>

Add support for trailing comma in function arguments

---

js2-mode.el
tests/parser.el

Currently, prefix unary nodes have their `pos` attribute set to the start of their argument rather than the start of the operator. This causes issues with `js2-node-at-point` and similar. This PR goes through all these node creation sites and sets the correct attribute. I guess it's technically a breaking change since it adds a non-optional argument to `js2-make-unary`, though that strikes me as an internal function.

Set the correct node pos for unary nodes

---

js2-mode.el

Currently `@type` is marked as a simple arg tag, rather than a curly-braced arg.
http://usejsdoc.org/tags-type.html

@type takes a curly-braced arg

---

js2-mode.el
tests/jsdoc.el

E.g.,
```js
/** @implements {Interface} */
var f = // ...
```

Highlight single line jsdoc comments

---

js2-mode.el

There's a little bit of a hack: [`@typedef`](usejsdoc.org/tags-typedef.html) is highlighted here the same way as [`@param`](http://usejsdoc.org/tags-param.html), though the grammars are technically different.
The grammar for `@typedef` is `@TAG [OPTIONAL-TYPE] NAME`, whereas `@param` technically has one extra production for the optional description (which js2 doesn't actually match on or highlight)

Add @typedef jsdoc highlighting support

---

js2-mode.el
tests/parser.el

Malformed import statements cause the parser to error:
```js
import * lib from 'lib';
```
This patch doesn't add anything in terms of parse-error recovery (the above has 7 parse errors), but it prevents the parser from crashing. I did run a couple of checks and the parser seems to always recover after the quoted source file.

Fix error when parsing malformed namespace import

---

js2-mode.el

Also, drop `(constructor nil)` on structures where a constructor is defined.

Fix length of shorthand object property nodes (e.g. `{foo,bar}`)

---

js2-mode.el
tests/navigation.el

There's a strange inconsistency when using `forward-sexp` and `backward-sexp`: Moving backwards takes you to the beginning of the string, whereas moving forwards skips over a symbol or balanced pair.
This patch makes `js2` more consistent with other modes by disabling its custom `forward-sexp` inside strings.

Use regular forward-sexp when inside strings

---

js2-mode.el

Not 100% sure this is correct, but I'm trying to set a couple of safe externs from a .dir-locals
file.

Allow safe additional-externs as file/dir-local

---

js2-mode.el

`cl-defstruct` no longer prefix struct names with `cl-struct-` in Emacs 26, this
has broken a couple of tests in [`rjsx-mode`](https://github.com/felipeochoa/rjsx-mode/issues/54), this PR fixes it.

Fix broken js2-node-short-name for Emacs 26

---

js2-mode.el
tests/navigation.el

This commit changes `js2-navigation-helper` to detect a specific error message thrown by `js2-jump-to-definition` rather than running it under `ignore-errors`.
Changing `js2-navigation-helper` exposes a bug on line 12751;  attempting to jump from an object property literal means that neither predicate on lines 12748, 12749 are true and so `js2-search-scope` is called with `names == '(nil)`.

allow testing for specific errors and add test for object property

---

NEWS.md
README.md
js2-mode.el

Since https://github.com/mooz/js2-mode/pull/523 won’t be merged, and as a follow-up to the changes you’ve made so far, I offer these additional documentation changes to compensate for the halfway-finished state of things.

JSX Documentation

---

NEWS.md
js2-mode.el
tests/parser.el

See https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining
and https://github.com/mooz/js2-mode/issues/506

support optional chaining operator

---

js2-mode.el

Because now we can, and it's consistent with how every other major modes for languages that have classes.

Use type face for class

---

tests/parser.el

Starting with Emacs 27, we have big integers, so the huge hexadecimal value is
parsed exactly.

Fix ‘huge-hex’ test for newer Emacsen.

---

tests/indent.el

Info node ‘(elisp) Local Variables’ states:
> […] the order of _bindings_ is unspecified: […] Therefore, avoid binding a
> variable more than once in a single ‘let’ form.
In fact, the tests that bind ‘js2-pretty-multiline-declarations’ twice fail if
indent.el is byte-compiles.

Avoid undefined behavior in indentation tests.

---

js2-imenu-extras.el

‘cl’ is now deprecated even when only used at compile time.

Migrate off deprecated ‘cl’ library.

---

js2-old-indent.el

This avoids a byte-compile warning.

Prefix an unused argument with an underscore.

---

js2-mode.el
tests/parser.el

feat(parser): add for-await-of parsing

---

NEWS.md
js2-mode.el
tests/parser.el

This implements [numeric separators in numbers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#numeric_separators).

Add support for numbers with numeric separator

---

js2-mode.el

The `js2-minor-mode-enter` adds `js2-minor-mode-edit` to `after-change-functions`. Contrary the `js2-minor-mode-exit` removes `js2-mode-edit` which had not been added to the list.
Without that, after enabling `js2-minor-mode` the `js-lint` remains enabled even when the mode exits.
I decided to go straight for a PR, as the issue looks like an obvious mistake, at first glance. Should that be not the case, apologies, for a naïve approach.

Remove the correct hook in js2-minor-mode-exit

---

NEWS.md
js2-mode.el
tests/parser.el

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#top_level_await
This is part of ECMAScript 2022: https://en.wikipedia.org/wiki/ECMAScript#ES2022

Support top-level await

---

js2-mode.el
tests/parser.el

When called with a statement function's name node,
js2-node-get-enclosing-scope would errorneously return the function itself.
That's not really the scope where this name is defined (it should be the
function's parent scope).
This bug affects js2-refactor's rename variable functionality.  Example:
(function(){
function |foo() {
var |foo = 5;
console.log(|foo);
}
foo();
})();
(where '|' marks possible cursor position).  Type M-x js2r-rename-var with
the cursor on one of the marked positions, and it'll offer to rename the
following occurrences (marked with underscores):
(function(){
function _foo_() {
var _foo_ = 5;
console.log(_foo_);
}
foo();
})();
This is incorrect, as the name is shadowed inside the function.  It should
instead rename these two:
(function(){
function _foo_() {
var foo = …

Fix js2-node-get-enclosing-scope on a statement function's name

---

js2-mode.el

This only replaces some deprecated code as js2-mode still declares
Emacs 24.1 as being supported.

Cleanup some deprecated code

---

js2-mode.el

Fixes parsing `export { foo as "some name" }`.
https://github.com/mishoo/UglifyJS/issues/5935#issuecomment-2335157622

fix parsing export { foo as "bar" }
